### ISSUE TITLE
Garbage chars displayed for (Abosulte) URI Record

### ISSUE THREAD

**Issue by afarber** [skjolber/ndef-tools-for-android#5]
Hello!

After installing nfc-eclipse-plugin I am trying to create Test.ndef file and add a record there: "Absolute URI Record" or "URI Record":

![eclipse](http://i.stack.imgur.com/wWSrX.png)

Then I try to scan the resulting QR image by using the popular ZXing [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) app.

Unfortunately the resulting QR image seems to contain 2 garbage chars:

![qr1](http://i.stack.imgur.com/dISGm.png)

![qr2](http://i.stack.imgur.com/8cFV9.png)

Why does it happen please?

**Comment by skjolber** [comment]
The eclipse plugin file editor uses a custom QR format and this is not readable by the usual barcode scanners. Basically the QR code contains the raw NDEF message as bytes.

Use the NFC Developer app from google play to read the codes.
