### ISSUE TITLE
NfcDetectorActivity should use onSaveInstanceState

### ISSUE THREAD

**Issue by michal-klimek** [skjolber/ndef-tools-for-android#6]
I run into a problem with NfcDetectorActivity. I completely understand tag dispatch system, and know that each onNewIntent call sets the new Intent as current activity intent. There is a field named "intentProcessed" which ensures no double detections of the same intent when activity is paused and resumed. A problem arises when you just change activity's orientation which in turn triggers (default) activity recreation, and when activity is resumed - tag detection callback is performed again. This leads to write failure callbacks in NfcTagWritterActivity as it thinks that a new tag is in range. I suggest to override onSaveInstanceState in NfcDetectorActivity and store intentProcessed value. This should be read in onCreate callback too. BTW. This project is awesome!

**Comment by skjolber** [comment]
Thanks for the report. Would you like to submit a pull request?

**Comment by skjolber** [comment]
Thanks for the pull request!
