### ISSUE TITLE
Question: Writing vCard etc

### ISSUE THREAD

**Issue by surewood** [skjolber/ndef-tools-for-android#8]
Hi,

first of all lovely lib. I was able to read&write tags in almost no time. I am now interested in writing vCards (phone numbers and contact name), website url, etc on tags. 

Can this awesome lib do this aswell? Tried finding some sample code for this purpose, but no luck.

**Comment by skjolber** [comment]
Hi, I've not tried vCards so much, but can you try 

https://github.com/mangstadt/ez-vcard

and see if that works using this lib? Perhaps a module and/or utility class or example would be a good idea.

**Comment by surewood** [comment]
skjolber, thanks for the reply! Will take a look at that looks promising!
